# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Client",
    "DataError",
    "DatabaseError",
    "Error",
    "InterfaceError",
    "InternalError",
    "MissingDependency",
    "OperationalError",
    "connect",
]

@typing.final
class Client:
    def query(self, query: builtins.str, *args: typing.Any) -> typing.Any: ...
    def execute(self, query: builtins.str, *args: typing.Any) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

class DataError(DatabaseError):
    ...

class DatabaseError(Error):
    ...

class Error(builtins.Exception):
    ...

class InterfaceError(Error):
    ...

class InternalError(DatabaseError):
    ...

class MissingDependency(InternalError):
    ...

class OperationalError(DatabaseError):
    ...

def connect(dsn: typing.Optional[builtins.str] = None, host: typing.Optional[builtins.str] = None, user: typing.Optional[builtins.str] = None, password: typing.Optional[builtins.str] = None, port: builtins.int = 5432, db: builtins.str = 'postgres') -> Client: ...

