# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Client",
    "connect",
    "sum_as_string",
]

@typing.final
class Client:
    def __repr__(self) -> builtins.str: ...

def connect(dsn: typing.Optional[builtins.str] = None, host: typing.Optional[builtins.str] = None, user: typing.Optional[builtins.str] = None, password: typing.Optional[builtins.str] = None, port: builtins.int = 5432, db: builtins.str = 'postgres') -> Client: ...

def sum_as_string(a: builtins.int, b: builtins.int) -> builtins.str: ...

